//
//  FixtureSeed.swift
//  NADE
//
//  The frozen world, and the reason it survived the move to a live client.
//
//  P2 ships a real HTTP client, so it would be reasonable to ask why the app
//  still carries fixtures. Three reasons, all of them about what the live
//  backend *cannot* show:
//
//  * `api/mail.rs` returns `agent_cards: []` and `agent_note: null` until
//    P4/P5, so 1f's agent card and 1e's accent note have no way to render
//    against a real server. Their screenshots can only come from here.
//  * A live mailbox changes hourly. Screenshots would never be reproducible,
//    and a UI test asserting a sender's name would fail on the next delivery.
//  * UI tests would need a running server and a paired device.
//
//  **The whole file is `#if DEBUG`.** That is the guarantee, not the byte
//  exclusion in the Release configuration — even if the JSON were present, a
//  release build has no code that can read it.
//

#if DEBUG
import Foundation
import os

nonisolated enum FixtureSeed {

    /// The manifest. Named here rather than enumerated from the bundle, so an
    /// empty or half-copied directory fails `FixtureParityTests` instead of
    /// making a per-file comparison vacuously true.
    static let names = [
        "me", "me_needs_reauth", "mailboxes",
        "threads", "threads_empty", "threads_last_page",
        "thread", "thread_html_only", "thread_partial",
        // `search.json` is the only page in the contract that carries the
        // partial thread's row, and a detail cannot be stored without one —
        // `applyThreadDetail` refuses to invent a list row out of a detail.
        // It backs the "To Reply" label, which is where `thread.json` and
        // `thread_partial.json` are both filed.
        "search",
        // P3.
        "feed", "feed_empty", "feed_item", "feed_item_info", "feed_item_editable",
        "agents", "agents_empty",
        "agent", "agent_draft", "agent_scheduled", "agent_compile_failed",
        "approve", "skip", "seen",
    ]

    /// The Ask streams, kept separate because they are **not** `.json`.
    ///
    /// `FixtureSeed.data` appends the extension, so a stream listed above would
    /// be looked up as `ask_answer.sse.json` and never found. Two lists and two
    /// extensions, rather than one list that is right for most of it.
    static let streamNames = [
        "ask_answer", "ask_results", "ask_agent_draft", "ask_error",
    ]

    /// **Which fixture backs which mailbox.**
    ///
    /// This was two literal `mailboxID ==` comparisons buried in a `switch`,
    /// and the reason `Label_12` mattered — that `mailboxes.json` names it "To
    /// Reply" and both thread details carry that `mailbox_name` — lived only in
    /// a comment. `docs/contract/` is regenerated by `generate.py`; when a
    /// rename lands, a table can be asserted and a `switch` cannot.
    /// `FixtureParityTests` checks every key and value against the fixtures.
    static let pages: [String: String] = [
        Mailbox.inbox: "threads",
        // "To Reply" — the label `thread.json` and `thread_partial.json` name
        // in `mailbox_name`, and the only page carrying the partial thread's row.
        Mailbox.toReply: "search",
        // "Subscriptions" — where `thread_html_only.json` is filed. Without a
        // page it had no list row, so `applyThreadDetail` skipped it and the
        // one thread exercising an emoji subject, a synthesised `body_text` and
        // `to: []` could not be opened at all. `FixtureParityTests` is what
        // noticed; `threads.json` carries its row.
        Mailbox.subscriptions: "threads",
    ]

    static let details = ["thread", "thread_html_only", "thread_partial"]

    /// The ids the launch arguments, the screenshots and the UI tests all name.
    enum Mailbox {
        static let inbox = "INBOX"
        static let sent = "SENT"
        static let toReply = "Label_12"
        static let subscriptions = "Label_1901000275082506782"
    }

    static let defaultThreadID = "18f2a1b3c4d5e6f7"

    static func data(_ name: String) throws -> Data {
        guard let url = Bundle.main.url(forResource: name, withExtension: "json") else {
            throw FixtureError.missing(name)
        }
        return try Data(contentsOf: url)
    }

    /// The raw bytes of an `.sse` fixture.
    static func stream(_ name: String) throws -> Data {
        guard let url = Bundle.main.url(forResource: name, withExtension: "sse") else {
            throw FixtureError.missing(name)
        }
        return try Data(contentsOf: url)
    }

    static func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try WireTime.decoder().decode(type, from: try data(name))
    }

    enum FixtureError: Error, Equatable {
        case missing(String)
    }

    /// Writes the fixture world straight into a store, without a source.
    ///
    /// This exists for one criterion: A16 asks what the app does when it is
    /// **relaunched against an unreachable server with mail already cached**,
    /// and that state cannot be reached by pointing the fixture source at a
    /// dead host — the fixture source always answers. So the rows go in
    /// directly and the live HTTP source is pointed at a closed port.
    static func seed(into store: MailStore, now: Date) async throws {
        try await store.upsertAccount(try decode(WireMe.self, "me"))
        try await store.replaceMailboxes(try decode(WireMailboxes.self, "mailboxes").mailboxes)
        for (mailboxID, page) in pages {
            try await store.applyThreadPage(
                try decode(WireThreadPage.self, page),
                mailboxID: mailboxID, resetting: true, now: now
            )
        }
        for detail in details {
            try await store.applyThreadDetail(try decode(WireThread.self, detail), now: now)
        }
    }
}

/// A `MailSource` that answers from the bundle.
///
/// It implements **every** endpoint, pairing included. A source that covered
/// only the reads would leave a fixture-mode Settings screen calling the real
/// network, and the hermetic world would not be hermetic.
nonisolated final class FixtureMailSource: MailSource {

    let origin = URL(string: "https://fixtures.nade.invalid")!
    let storeLocation: StoreLocation = .fixtures

    /// `-NADESeed empty` — the same code path, nothing in it. Renders the
    /// empty states without a second app target or a mocked network.
    let isEmpty: Bool

    /// Scoped rather than `NSLock`: `lock()` is unavailable from an async
    /// context (and an error in Swift 6), and every caller here is async.
    private struct State: Sendable {
        var paired: Bool
        var gmailLinked: Bool
    }
    private let state: OSAllocatedUnfairLock<State>

    init(isEmpty: Bool, paired: Bool = true, gmailLinked: Bool = true) {
        self.isEmpty = isEmpty
        self.state = OSAllocatedUnfairLock(initialState: State(paired: paired, gmailLinked: gmailLinked))
    }

    func isPaired() throws -> Bool {
        state.withLock { $0.paired }
    }

    // MARK: - P3

    func feed(cursor: String?) async throws -> WireFeedPage {
        try FixtureSeed.decode(WireFeedPage.self, isEmpty ? "feed_empty" : "feed")
    }

    func feedItem(id: String) async throws -> WireFeedItem {
        let page = try FixtureSeed.decode(WireFeedPage.self, "feed")
        guard let item = page.items.first(where: { $0.id == id }) else {
            throw APIFailure.server(code: .notFound, status: 404,
                                    message: "No such feed item.", retryAfter: nil)
        }
        return item
    }

    /// The fixture world answers an approve the way the server would, so the
    /// outbox's success path is exercised rather than stubbed.
    func approve(feedItemID: String, approvalToken: String) async throws -> WireApproveResponse {
        try FixtureSeed.decode(WireApproveResponse.self, "approve")
    }

    func skip(feedItemID: String, approvalToken: String) async throws -> WireSkipResponse {
        try FixtureSeed.decode(WireSkipResponse.self, "skip")
    }

    func seen(ids: [String]) async throws -> WireSeenResponse {
        try FixtureSeed.decode(WireSeenResponse.self, "seen")
    }

    func agents() async throws -> [WireAgentRow] {
        try FixtureSeed.decode(WireAgentList.self, isEmpty ? "agents_empty" : "agents").agents
    }

    func pair(code: String, deviceName: String) async throws -> Credential {
        // Mirrors the server: six ASCII digits or it is a 400, and any other
        // code is the same indistinguishable 401 the real endpoint returns.
        guard code.count == 6, code.allSatisfy(\.isNumber) else {
            throw APIFailure.server(code: .badRequest, status: 400,
                                    message: "That code should be six digits.", retryAfter: nil)
        }
        state.withLock { $0.paired = true }
        return Credential(baseURL: origin, token: "nade_" + String(repeating: "f", count: 64))
    }

    func unpair() throws {
        state.withLock { $0.paired = false }
    }

    func me() async throws -> WireMe {
        if isEmpty { return WireMe(email: "", status: .needsReauth) }
        let linked = state.withLock { $0.gmailLinked }
        return try FixtureSeed.decode(WireMe.self, linked ? "me" : "me_needs_reauth")
    }

    func gmailLink() async throws -> WireGmailLink {
        state.withLock { $0.gmailLinked = true }
        return WireGmailLink(url: origin.appendingPathComponent("v1/auth/gmail/start").absoluteString,
                             expiresAt: Date())
    }

    func mailboxes() async throws -> [WireMailbox] {
        if isEmpty { return [] }
        return try FixtureSeed.decode(WireMailboxes.self, "mailboxes").mailboxes
    }

    func threads(mailboxID: String, cursor: String?) async throws -> WireThreadPage {
        if isEmpty { return try FixtureSeed.decode(WireThreadPage.self, "threads_empty") }
        // Only INBOX has a page in the fixture world; every other label is a
        // real, legal empty mailbox, which is a state worth being able to see.
        guard let page = FixtureSeed.pages[mailboxID] else {
            // Every other label is a real, legal empty mailbox — a state worth
            // being able to see.
            return try FixtureSeed.decode(WireThreadPage.self, "threads_empty")
        }
        // Page two is the last page, so load-more is exercisable by hand.
        if cursor != nil {
            return try FixtureSeed.decode(WireThreadPage.self, "threads_last_page")
        }
        return try FixtureSeed.decode(WireThreadPage.self, page)
    }

    func thread(id: String) async throws -> WireThread {
        for name in FixtureSeed.details {
            let candidate = try FixtureSeed.decode(WireThread.self, name)
            if candidate.id == id { return candidate }
        }
        throw APIFailure.server(code: .notFound, status: 404,
                                message: "That conversation is not in this mailbox.", retryAfter: nil)
    }
}
#endif
