//
//  FixtureSeed.swift
//  NADE
//
//  The frozen world, and the reason it survived the move to a live client.
//
//  P2 ships a real HTTP client, so it would be reasonable to ask why the app
//  still carries fixtures. Three reasons, all of them about what the live
//  backend *cannot* show:
//
//  * `api/mail.rs` returns `agent_cards: []` and `agent_note: null` until
//    P4/P5, so 1f's agent card and 1e's accent note have no way to render
//    against a real server. Their screenshots can only come from here.
//  * A live mailbox changes hourly. Screenshots would never be reproducible,
//    and a UI test asserting a sender's name would fail on the next delivery.
//  * UI tests would need a running server and a paired device.
//
//  **The whole file is `#if DEBUG`.** That is the guarantee, not the byte
//  exclusion in the Release configuration — even if the JSON were present, a
//  release build has no code that can read it.
//

#if DEBUG
import Foundation
import os

nonisolated enum FixtureSeed {

    /// The manifest. Named here rather than enumerated from the bundle, so an
    /// empty or half-copied directory fails `FixtureParityTests` instead of
    /// making a per-file comparison vacuously true.
    static let names = [
        "me", "me_needs_reauth", "mailboxes",
        "threads", "threads_empty", "threads_last_page",
        "thread", "thread_html_only", "thread_partial",
        // `search.json` is the only page in the contract that carries the
        // partial thread's row, and a detail cannot be stored without one —
        // `applyThreadDetail` refuses to invent a list row out of a detail.
        // It backs the "To Reply" label, which is where `thread.json` and
        // `thread_partial.json` are both filed.
        "search",
        // P3.
        "feed", "feed_empty", "feed_item", "feed_item_info", "feed_item_editable",
        "agents", "agents_empty",
        "agent", "agent_draft", "agent_scheduled", "agent_compile_failed",
        "approve", "skip", "seen",
    ]

    /// The Ask streams, kept separate because they are **not** `.json`.
    ///
    /// `FixtureSeed.data` appends the extension, so a stream listed above would
    /// be looked up as `ask_answer.sse.json` and never found. Two lists and two
    /// extensions, rather than one list that is right for most of it.
    static let streamNames = [
        "ask_answer", "ask_results", "ask_agent_draft", "ask_error",
    ]

    /// **Which fixture backs which mailbox.**
    ///
    /// This was two literal `mailboxID ==` comparisons buried in a `switch`,
    /// and the reason `Label_12` mattered — that `mailboxes.json` names it "To
    /// Reply" and both thread details carry that `mailbox_name` — lived only in
    /// a comment. `docs/contract/` is regenerated by `generate.py`; when a
    /// rename lands, a table can be asserted and a `switch` cannot.
    /// `FixtureParityTests` checks every key and value against the fixtures.
    static let pages: [String: String] = [
        Mailbox.inbox: "threads",
        // "To Reply" — the label `thread.json` and `thread_partial.json` name
        // in `mailbox_name`, and the only page carrying the partial thread's row.
        Mailbox.toReply: "search",
        // "Subscriptions" — where `thread_html_only.json` is filed. Without a
        // page it had no list row, so `applyThreadDetail` skipped it and the
        // one thread exercising an emoji subject, a synthesised `body_text` and
        // `to: []` could not be opened at all. `FixtureParityTests` is what
        // noticed; `threads.json` carries its row.
        Mailbox.subscriptions: "threads",
    ]

    static let details = ["thread", "thread_html_only", "thread_partial"]

    /// The ids the launch arguments, the screenshots and the UI tests all name.
    enum Mailbox {
        static let inbox = "INBOX"
        static let sent = "SENT"
        static let toReply = "Label_12"
        static let subscriptions = "Label_1901000275082506782"
    }

    static let defaultThreadID = "18f2a1b3c4d5e6f7"
    /// `agent.json` — the published, fully compiled one, so `-NADEScreen 1c`
    /// lands on the state with underlines rather than the compile-failure
    /// fallback.
    static let defaultAgentID = "a0000001-0000-4000-8000-000000000001"

    static func data(_ name: String) throws -> Data {
        guard let url = Bundle.main.url(forResource: name, withExtension: "json") else {
            throw FixtureError.missing(name)
        }
        return try Data(contentsOf: url)
    }

    /// The raw bytes of an `.sse` fixture.
    static func stream(_ name: String) throws -> Data {
        guard let url = Bundle.main.url(forResource: name, withExtension: "sse") else {
            throw FixtureError.missing(name)
        }
        return try Data(contentsOf: url)
    }

    static func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try WireTime.decoder().decode(type, from: try data(name))
    }

    enum FixtureError: Error, Equatable {
        case missing(String)
    }

    /// Writes the fixture world straight into a store, without a source.
    ///
    /// This exists for one criterion: A16 asks what the app does when it is
    /// **relaunched against an unreachable server with mail already cached**,
    /// and that state cannot be reached by pointing the fixture source at a
    /// dead host — the fixture source always answers. So the rows go in
    /// directly and the live HTTP source is pointed at a closed port.
    static func seed(into store: MailStore, now: Date) async throws {
        try await store.upsertAccount(try decode(WireMe.self, "me"))
        try await store.replaceMailboxes(try decode(WireMailboxes.self, "mailboxes").mailboxes)
        for (mailboxID, page) in pages {
            try await store.applyThreadPage(
                try decode(WireThreadPage.self, page),
                mailboxID: mailboxID, resetting: true, now: now
            )
        }
        for detail in details {
            try await store.applyThreadDetail(try decode(WireThread.self, detail), now: now)
        }
    }
}

/// A `MailSource` that answers from the bundle.
///
/// It implements **every** endpoint, pairing included. A source that covered
/// only the reads would leave a fixture-mode Settings screen calling the real
/// network, and the hermetic world would not be hermetic.
nonisolated final class FixtureMailSource: MailSource {

    let origin = URL(string: "https://fixtures.nade.invalid")!
    let storeLocation: StoreLocation = .fixtures

    /// `-NADESeed empty` — the same code path, nothing in it. Renders the
    /// empty states without a second app target or a mocked network.
    let isEmpty: Bool

    /// Scoped rather than `NSLock`: `lock()` is unavailable from an async
    /// context (and an error in Swift 6), and every caller here is async.
    private struct State: Sendable {
        var paired: Bool
        var gmailLinked: Bool
        /// Nil until first read. The agent screens *write* — publish, toggle
        /// approval, edit a sentence, delete — and a source that re-decoded the
        /// fixture on every call would show every one of those edits being
        /// silently discarded, which is a worse lie than an empty list.
        var agents: [WireAgent]?
        /// Same, for the feed. Approve and skip are **terminal**: the card must
        /// lose its token and stop being `new`, or the outbox's own refetch
        /// restores the card it just resolved and the approval can be replayed.
        var feed: [WireFeedItem]?
        var newCount: Int?
    }
    private let state: OSAllocatedUnfairLock<State>

    init(isEmpty: Bool, paired: Bool = true, gmailLinked: Bool = true) {
        self.isEmpty = isEmpty
        self.state = OSAllocatedUnfairLock(initialState: State(paired: paired,
                                                               gmailLinked: gmailLinked,
                                                               agents: nil,
                                                               feed: nil,
                                                               newCount: nil))
    }

    func isPaired() throws -> Bool {
        state.withLock { $0.paired }
    }

    // MARK: - P3

    func feed(cursor: String?) async throws -> WireFeedPage {
        let items = try loadedFeed()
        return WireFeedPage(items: items, nextCursor: nil, newCount: try currentNewCount())
    }

    func feedItem(id: String) async throws -> WireFeedItem {
        guard let item = try loadedFeed().first(where: { $0.id == id }) else {
            throw APIFailure.server(code: .notFound, status: 404,
                                    message: "No such feed item.", retryAfter: nil)
        }
        return item
    }

    /// The fixture world answers an approve the way the server would — and,
    /// crucially, **moves the card**.
    ///
    /// Returning a canned success while leaving the fixture untouched made every
    /// terminal action undo itself: the outbox re-fetches the item after a
    /// success, got the original `new` row with its token back, and the card
    /// returned to the feed still approvable. A replay of a consumed token is
    /// exactly what `API.md` §7's 409 exists to prevent, so the fixture has to
    /// be able to reach that state.
    func approve(feedItemID: String, approvalToken: String) async throws -> WireApproveResponse {
        try resolve(feedItemID, token: approvalToken, status: .resolved,
                    note: "Saved.")
        return try FixtureSeed.decode(WireApproveResponse.self, "approve")
    }

    func skip(feedItemID: String, approvalToken: String) async throws -> WireSkipResponse {
        try resolve(feedItemID, token: approvalToken, status: .skipped,
                    note: "Skipped.")
        return try FixtureSeed.decode(WireSkipResponse.self, "skip")
    }

    func seen(ids: [String]) async throws -> WireSeenResponse {
        try mutateFeed { items in
            for (index, item) in items.enumerated()
            where ids.contains(item.id) && item.kind == .info && item.status == .new {
                items[index] = Self.resolved(item, status: .resolved, note: item.resolvedNote)
            }
        }
        return WireSeenResponse(newCount: try currentNewCount())
    }

    /// A terminal action, with the contract's own replay rule.
    ///
    /// A second attempt with a spent token is a **409 `token_consumed`**, which
    /// the client treats as success — not a silent second approval.
    private func resolve(_ id: String, token: String,
                         status: FeedStatus, note: String) throws {
        var outcome: APIFailure?
        try mutateFeed { items in
            guard let index = items.firstIndex(where: { $0.id == id }) else {
                outcome = APIFailure.server(code: .notFound, status: 404,
                                            message: "No such feed item.", retryAfter: nil)
                return
            }
            guard items[index].approvalToken == token else {
                outcome = APIFailure.server(code: .tokenConsumed, status: 409,
                                            message: "That approval was already answered.",
                                            retryAfter: nil)
                return
            }
            items[index] = Self.resolved(items[index], status: status, note: note)
        }
        if let outcome { throw outcome }
    }

    /// Terminal means terminal: the token is gone and `actions` is empty, which
    /// is what `API.md` §7 says of anything resolved, skipped or expired.
    private static func resolved(_ item: WireFeedItem,
                                 status: FeedStatus, note: String?) -> WireFeedItem {
        WireFeedItem(id: item.id, kind: item.kind, title: item.title, body: item.body,
                     status: status, runID: item.runID, actions: [],
                     approvalToken: nil, approvalExpiresAt: item.approvalExpiresAt,
                     resolvedNote: note ?? item.resolvedNote, data: item.data,
                     createdAt: item.createdAt)
    }

    private func loadedFeed() throws -> [WireFeedItem] {
        if let existing = state.withLock({ $0.feed }) { return existing }
        let page = try FixtureSeed.decode(WireFeedPage.self, isEmpty ? "feed_empty" : "feed")
        return state.withLock { current in
            if let existing = current.feed { return existing }
            current.feed = page.items
            current.newCount = page.newCount
            return page.items
        }
    }

    private func mutateFeed(_ body: (inout [WireFeedItem]) -> Void) throws {
        _ = try loadedFeed()
        state.withLock { current in
            var items = current.feed ?? []
            body(&items)
            current.feed = items
        }
    }

    /// Recomputed from the rows, so answering a card moves the badge — which is
    /// the whole reason `new_count` is on the page.
    private func currentNewCount() throws -> Int {
        try loadedFeed().count { $0.status == .new }
    }

    func agents() async throws -> [WireAgentRow] {
        try loadedAgents().map(Self.row(from:))
    }

    func agent(id: String) async throws -> WireAgent {
        guard let found = try loadedAgents().first(where: { $0.id == id }) else {
            throw APIFailure.server(code: .notFound, status: 404,
                                    message: "That agent no longer exists.", retryAfter: nil)
        }
        return found
    }

    /// Mirrors the server's one non-negotiable rule: **a created agent is always
    /// a draft** (`API.md` §5). The fixture cannot let a caller ask for
    /// `published`, because the Ask screen's promise - "It won't run until you
    /// publish it" - is the thing being demonstrated.
    func createAgent(nlDefinition: String) async throws -> WireAgent {
        guard !nlDefinition.nadeIsBlank else {
            throw APIFailure.server(code: .badRequest, status: 400,
                                    message: "An agent needs a sentence.", retryAfter: nil)
        }
        let template = try FixtureSeed.decode(WireAgent.self, "agent_draft")
        let created = WireAgent(
            id: UUID().uuidString.lowercased(),
            name: Self.name(from: nlDefinition) ?? template.name,
            nlDefinition: nlDefinition,
            status: .draft,
            triggerSummary: template.triggerSummary,
            schedule: template.schedule,
            lastRunAt: nil,
            approvalRequired: template.approvalRequired,
            allowedTools: template.allowedTools,
            compileError: nil,
            whenSpan: template.whenSpan,
            doSpan: template.doSpan,
            trailing: template.trailing,
            spec: template.spec
        )
        // **Appended, not prepended.** `API.md` §5 orders `GET /agents` oldest
        // first, and the order is persisted verbatim as `AgentRecord.position`,
        // so putting new agents at the top here would have taught the demo world
        // an order the live backend will not reproduce.
        try mutateAgents { $0.append(created) }
        return created
    }

    func updateAgent(id: String, patch: AgentPatch) async throws -> WireAgent {
        var updated: WireAgent?
        try mutateAgents { agents in
            guard let index = agents.firstIndex(where: { $0.id == id }) else { return }
            agents[index] = Self.apply(patch, to: agents[index])
            updated = agents[index]
        }
        guard let updated else {
            throw APIFailure.server(code: .notFound, status: 404,
                                    message: "That agent no longer exists.", retryAfter: nil)
        }
        return updated
    }

    func deleteAgent(id: String) async throws {
        var removed = false
        try mutateAgents { agents in
            let before = agents.count
            agents.removeAll { $0.id == id }
            removed = agents.count != before
        }
        guard removed else {
            throw APIFailure.server(code: .notFound, status: 404,
                                    message: "That agent no longer exists.", retryAfter: nil)
        }
    }

    /// `API.md` §6: a manual run works on a **draft** too - that is what the
    /// builder's "Run once now" is for - and it does not advance `runs_done`.
    func runAgent(id: String) async throws -> WireRunStarted {
        _ = try await agent(id: id)
        return WireRunStarted(runID: UUID().uuidString.lowercased())
    }

    /// Replays a checked-in `.sse` fixture through the **real** parser.
    ///
    /// Not a hand-built array of events: `docs/contract/*.sse` are the bytes the
    /// server promises, `SSEParser` is the code that will read them at P6, and
    /// a fixture that skipped the parser would let a framing bug ship.
    func ask(query: String, threadID: String?, routeHint: AskRoute?)
        -> AsyncThrowingStream<AskEvent, any Error> {
        AsyncThrowingStream { continuation in
            do {
                let name = Self.streamName(query: query, routeHint: routeHint)
                var parser = SSEParser()
                for event in try parser.consume(try FixtureSeed.stream(name)) {
                    continuation.yield(event)
                }
                for event in try parser.finish() {
                    continuation.yield(event)
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }

    /// Which fixture answers this query.
    ///
    /// `routeHint` wins, because that is exactly what `API.md` §4 says it does -
    /// it "forces the route instead of letting the server classify" and is the
    /// whole reason 1a's "Make this an agent" button can exist. Everything else
    /// mimics the server's documented heuristics-first order: quoted strings and
    /// `from:` are a search, imperative time words are an agent, else an answer.
    private static func streamName(query: String, routeHint: AskRoute?) -> String {
        if let routeHint {
            switch routeHint {
            case .agentDraft: return "ask_agent_draft"
            case .results: return "ask_results"
            case .answer: return "ask_answer"
            case .unknown: return "ask_error"
            }
        }
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        // EDGE: empty input. The field disables its button, so reaching here at
        // all is a caller bug - and the contract has an error stream for it.
        if trimmed.isEmpty { return "ask_error" }
        let lowered = trimmed.lowercased()
        // Agent first: "Every weekday, …" starts with a word the search branch
        // would otherwise claim.
        if ["when ", "every ", "each ", "whenever "].contains(where: lowered.hasPrefix) {
            return "ask_agent_draft"
        }
        // `from:` and quoted strings are the two heuristics `PLAN.md` §Ask
        // routing names. `find ` is added for the fixture world only: the real
        // server falls through to a cheap model, which this cannot do, and
        // without it `DESIGN.md` §4's second focus prompt ("Find every receipt
        // from last month") routed to `answer` — leaving the `results` state
        // unreachable from 2a, which is the one thing the three prompts exist
        // to prove.
        if lowered.contains("from:") || trimmed.contains("\"") || lowered.hasPrefix("find ") {
            return "ask_results"
        }
        return "ask_answer"
    }

    // MARK: - The mutable agent world

    private func loadedAgents() throws -> [WireAgent] {
        if let existing = state.withLock({ $0.agents }) { return existing }
        let loaded = try Self.seedAgents(isEmpty: isEmpty)
        // EDGE: two concurrent first reads. Whoever writes second must not
        // clobber edits the first one's caller has already made, so the write
        // only fills a still-empty slot.
        return state.withLock { current in
            if let existing = current.agents { return existing }
            current.agents = loaded
            return loaded
        }
    }

    private func mutateAgents(_ body: (inout [WireAgent]) -> Void) throws {
        _ = try loadedAgents()
        state.withLock { current in
            var agents = current.agents ?? []
            body(&agents)
            current.agents = agents
        }
    }

    /// The four detail fixtures are the four rows of `agents.json`, so the list
    /// and the detail cannot drift - open any row and the object behind it is
    /// the one the contract ships.
    private static func seedAgents(isEmpty: Bool) throws -> [WireAgent] {
        guard !isEmpty else { return [] }
        let order = try FixtureSeed.decode(WireAgentList.self, "agents").agents.map(\.id)
        let details = ["agent", "agent_scheduled", "agent_draft", "agent_compile_failed"]
            .compactMap { try? FixtureSeed.decode(WireAgent.self, $0) }
        return order.compactMap { id in details.first { $0.id == id } }
    }

    private static func row(from agent: WireAgent) -> WireAgentRow {
        WireAgentRow(id: agent.id,
                     name: agent.name,
                     nlDefinition: agent.nlDefinition,
                     status: agent.status,
                     triggerSummary: agent.triggerSummary,
                     schedule: agent.schedule,
                     lastRunAt: agent.lastRunAt,
                     approvalRequired: agent.approvalRequired)
    }

    /// Only the five fields `PATCH` accepts.
    ///
    /// **A changed `nl_definition` re-derives the spans.** `API.md` §5 says
    /// changing it recompiles `spec` and returns fresh `when_span` / `do_span`,
    /// and carrying the old ones over made every sentence edit look like it had
    /// failed: the stored definition changed while 1c kept rendering the words
    /// the user had just replaced. There is no compiler here, so the spans are
    /// split back out of the sentence the screen composed — the exact inverse of
    /// `AgentBuilderModel.compose`, which is enough to keep the round trip
    /// honest.
    private static func apply(_ patch: AgentPatch, to agent: WireAgent) -> WireAgent {
        let sentence = patch.nlDefinition
        let spans = sentence.flatMap(decompose(_:))
        return WireAgent(id: agent.id,
                         name: sentence.flatMap(name(from:)) ?? agent.name,
                         nlDefinition: sentence ?? agent.nlDefinition,
                         status: patch.status ?? agent.status,
                         triggerSummary: agent.triggerSummary,
                         schedule: patch.schedule ?? agent.schedule,
                         lastRunAt: agent.lastRunAt,
                         approvalRequired: patch.approvalRequired ?? agent.approvalRequired,
                         allowedTools: patch.allowedTools ?? agent.allowedTools,
                         // A sentence that no longer parses is a compile
                         // failure, which is a state 1c already renders.
                         compileError: sentence == nil ? agent.compileError
                             : (spans == nil ? "Couldn't read that as a rule." : nil),
                         whenSpan: sentence == nil ? agent.whenSpan : spans?.when,
                         doSpan: sentence == nil ? agent.doSpan : spans?.doing,
                         trailing: sentence == nil ? agent.trailing : spans?.trailing,
                         spec: sentence == nil ? agent.spec : (spans == nil ? nil : agent.spec))
    }

    /// `When {when}, {do}.` plus an optional trailing sentence, split back out.
    ///
    /// Returns nil when the sentence is not that shape, which is what makes the
    /// compile-failure path reachable from the builder.
    private static func decompose(
        _ sentence: String
    ) -> (when: String, doing: String, trailing: String?)? {
        let trimmed = sentence.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.lowercased().hasPrefix("when ") else { return nil }
        let body = String(trimmed.dropFirst("when ".count))
        // The period is searched for **after the comma**, and only one that ends
        // a clause counts.
        //
        // Two ways the naive version got this wrong. `firstIndex(of: ".")` over
        // the whole string found the dot in "When stripe.com emails, …" and gave
        // up, dropping 1c to its compile-failure fallback for a good sentence.
        // `lastIndex` then swung the other way and swallowed the trailing
        // sentence into the `do` span. A clause-ending period is one at the end
        // of the string or followed by whitespace — which "stripe.com" is not.
        guard let comma = body.firstIndex(of: ",") else { return nil }
        let afterComma = body.index(after: comma)
        guard let stop = body[afterComma...].indices.first(where: { index in
            guard body[index] == "." else { return false }
            let next = body.index(after: index)
            return next == body.endIndex || body[next].isWhitespace
        }) else { return nil }
        let when = String(body[body.startIndex..<comma])
            .trimmingCharacters(in: .whitespaces)
        let doing = String(body[body.index(after: comma)..<stop])
            .trimmingCharacters(in: .whitespaces)
        let rest = String(body[body.index(after: stop)...])
            .trimmingCharacters(in: .whitespaces)
        guard !when.isEmpty, !doing.isEmpty else { return nil }
        return (when, doing, rest.isEmpty ? nil : rest)
    }

    /// A readable stand-in for the strong model's naming step, so a created
    /// agent is not called "Reply Drafter" whatever you typed.
    private static func name(from nlDefinition: String) -> String? {
        let words = nlDefinition
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .split(whereSeparator: { $0 == " " || $0 == "\n" })
            .prefix(4)
        guard !words.isEmpty else { return nil }
        return words.joined(separator: " ").capitalized
    }

    func pair(code: String, deviceName: String) async throws -> Credential {
        // Mirrors the server: six ASCII digits or it is a 400, and any other
        // code is the same indistinguishable 401 the real endpoint returns.
        guard code.count == 6, code.allSatisfy(\.isNumber) else {
            throw APIFailure.server(code: .badRequest, status: 400,
                                    message: "That code should be six digits.", retryAfter: nil)
        }
        state.withLock { $0.paired = true }
        return Credential(baseURL: origin, token: "nade_" + String(repeating: "f", count: 64))
    }

    func unpair() throws {
        state.withLock { $0.paired = false }
    }

    func me() async throws -> WireMe {
        if isEmpty { return WireMe(email: "", status: .needsReauth) }
        let linked = state.withLock { $0.gmailLinked }
        return try FixtureSeed.decode(WireMe.self, linked ? "me" : "me_needs_reauth")
    }

    func gmailLink() async throws -> WireGmailLink {
        state.withLock { $0.gmailLinked = true }
        return WireGmailLink(url: origin.appendingPathComponent("v1/auth/gmail/start").absoluteString,
                             expiresAt: Date())
    }

    func mailboxes() async throws -> [WireMailbox] {
        if isEmpty { return [] }
        return try FixtureSeed.decode(WireMailboxes.self, "mailboxes").mailboxes
    }

    func threads(mailboxID: String, cursor: String?) async throws -> WireThreadPage {
        if isEmpty { return try FixtureSeed.decode(WireThreadPage.self, "threads_empty") }
        // Only INBOX has a page in the fixture world; every other label is a
        // real, legal empty mailbox, which is a state worth being able to see.
        guard let page = FixtureSeed.pages[mailboxID] else {
            // Every other label is a real, legal empty mailbox — a state worth
            // being able to see.
            return try FixtureSeed.decode(WireThreadPage.self, "threads_empty")
        }
        // Page two is the last page, so load-more is exercisable by hand.
        if cursor != nil {
            return try FixtureSeed.decode(WireThreadPage.self, "threads_last_page")
        }
        return try FixtureSeed.decode(WireThreadPage.self, page)
    }

    /// The fixture world has no bytes to serve, so it writes a small text file
    /// with the name that was asked for. Enough to prove the tap, the download
    /// state and the preview sheet, without pretending to be a real PDF.
    func downloadAttachment(gmailID: String, attachmentID: String, filename: String)
        async throws -> URL {
        let directory = URL.temporaryDirectory.appendingPathComponent(UUID().uuidString,
                                                                      isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        var safe = (filename as NSString).lastPathComponent
        if safe.isEmpty { safe = "attachment" }
        let destination = directory.appendingPathComponent(safe)
        try Data("This is a fixture attachment.\n".utf8).write(to: destination)
        return destination
    }

    /// A 1×1 transparent PNG, so the fixture world's "View original" renders a
    /// real image element rather than a broken one.
    func attachmentData(gmailID: String, attachmentID: String) async throws -> Data {
        Data(base64Encoded: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=")!
    }

    func thread(id: String) async throws -> WireThread {
        for name in FixtureSeed.details {
            let candidate = try FixtureSeed.decode(WireThread.self, name)
            if candidate.id == id { return candidate }
        }
        throw APIFailure.server(code: .notFound, status: 404,
                                message: "That conversation is not in this mailbox.", retryAfter: nil)
    }
}
#endif
