//
//  FixtureParityTests.swift
//  NADETests
//
//  P2 A5. The app bundles nine of `docs/contract/`'s fixtures so the DEBUG
//  world can render without a server. Two copies of a file is two places for
//  the truth to live, so this is what keeps them one.
//
//  **The manifest is asserted, not just each file.** A per-file loop over
//  whatever happens to be in `NADE/Fixtures/mail/` passes over an empty
//  directory, which is the failure mode most likely to arrive — a half-finished
//  copy, or a rename on the contract side that nobody mirrored.
//

import XCTest
@testable import NADE

final class FixtureParityTests: XCTestCase {

    private func appFixtureDirectory() throws -> URL {
        try ContractFixture.repoDirectory("NADE/Fixtures/mail")
    }

    /// The set, both ways. A missing copy and a stray extra both fail.
    func testTheBundledSetIsExactlyTheManifest() throws {
        let onDisk = Set(
            try FileManager.default.contentsOfDirectory(atPath: try appFixtureDirectory().path)
                .filter { ($0 as NSString).pathExtension == "json" }
                .map { ($0 as NSString).deletingPathExtension }
        )
        XCTAssertEqual(onDisk, Set(FixtureSeed.names),
                       "NADE/Fixtures/mail does not match FixtureSeed.names")
        XCTAssertEqual(FixtureSeed.names.count, 10)
    }

    /// Three-way: the contract, the copy, and what actually reached the app.
    /// `Bundle.main` is the app bundle in these host-app tests, which is what
    /// `InfoPlistTests` already relies on.
    func testEveryBundledFixtureIsByteIdenticalToTheContract() throws {
        let appDirectory = try appFixtureDirectory()
        let contractDirectory = try ContractFixture.directory()

        for name in FixtureSeed.names {
            let contract = try Data(contentsOf: contractDirectory.appendingPathComponent("\(name).json"))
            let copy = try Data(contentsOf: appDirectory.appendingPathComponent("\(name).json"))
            XCTAssertEqual(copy, contract,
                           "NADE/Fixtures/mail/\(name).json has drifted from docs/contract/\(name).json")

            let bundled = try FixtureSeed.data(name)
            XCTAssertEqual(bundled, contract,
                           "\(name).json reached the app bundle with different bytes")
        }
    }

    /// The bundle is flat — `docs/contract` lands flat in `NADETests.xctest`
    /// (D4) and `NADE/Fixtures/mail` lands flat in `NADE.app` beside
    /// `calendar.json`. Nothing collides today; this is what says so if a later
    /// phase adds a resource that would.
    func testNoTwoJSONResourcesInTheAppShareAName() throws {
        let urls = Bundle.main.urls(forResourcesWithExtension: "json", subdirectory: nil) ?? []
        let names = urls.map { $0.deletingPathExtension().lastPathComponent }
        XCTAssertEqual(Set(names).count, names.count, "two JSON resources share a name: \(names.sorted())")
        XCTAssertTrue(Set(names).isSuperset(of: Set(FixtureSeed.names)))
        XCTAssertTrue(names.contains("calendar"), "the P7 calendar stub is still the one shipping fixture")
    }

    /// Every bundled fixture decodes through the app's own decoder. A copy that
    /// is byte-identical but unreadable by the seeder would still break the
    /// DEBUG world, and the parity check alone would not notice.
    ///
    /// Driven off `FixtureSeed.names` rather than a second hand-written list —
    /// which is the argument this file's own header makes about the manifest.
    func testEveryBundledFixtureDecodes() throws {
        for name in FixtureSeed.names {
            let data = try FixtureSeed.data(name)
            XCTAssertNoThrow(try JSONSerialization.jsonObject(with: data), name)
        }
        // …and each shape decodes into the model that reads it.
        XCTAssertNoThrow(try FixtureSeed.decode(WireMe.self, "me"))
        XCTAssertNoThrow(try FixtureSeed.decode(WireMailboxes.self, "mailboxes"))
        for page in FixtureSeed.pages.values {
            XCTAssertNoThrow(try FixtureSeed.decode(WireThreadPage.self, page), page)
        }
        for detail in FixtureSeed.details {
            XCTAssertNoThrow(try FixtureSeed.decode(WireThread.self, detail), detail)
        }
    }

    /// A3. `FixtureSeed.pages` says which fixture backs which mailbox, and its
    /// keys only mean anything because `mailboxes.json` names them. That was a
    /// comment; `docs/contract/` is regenerated by `generate.py`, and when a
    /// rename lands a table can be asserted where a comment cannot — the
    /// symptom otherwise is three blank screenshots and five UI tests failing
    /// with "element does not exist", pointing nowhere near the fixture.
    func testTheFixtureWorldsMappingResolvesAgainstTheContract() throws {
        let mailboxes = try ContractFixture.mailboxes()
        for (mailboxID, page) in FixtureSeed.pages {
            XCTAssertTrue(mailboxes.contains { $0.id == mailboxID },
                          "\(mailboxID) backs a fixture page but is not a mailbox")
            XCTAssertTrue(FixtureSeed.names.contains(page),
                          "\(mailboxID) is backed by \(page), which the app does not bundle")
        }

        // Every detail is filed under a label that has a page, which is what
        // makes it reachable at all.
        for detail in FixtureSeed.details {
            let thread = try FixtureSeed.decode(WireThread.self, detail)
            let named = mailboxes.first { $0.name == thread.mailboxName }
            let mailboxID = try XCTUnwrap(named?.id, "\(detail) is filed under \(thread.mailboxName), which is not a mailbox")
            XCTAssertNotNil(FixtureSeed.pages[mailboxID],
                            "\(detail) is filed under \(thread.mailboxName), which has no page — it is unreachable")
        }

        XCTAssertTrue(mailboxes.contains { $0.id == FixtureSeed.Mailbox.sent })
        XCTAssertEqual(try FixtureSeed.decode(WireThread.self, "thread").id,
                       FixtureSeed.defaultThreadID,
                       "the thread the screenshots open by default is not thread.json's")
    }
}
